export const SET_STOCK_DATA = 'SET_STOCK_DATA';
export const FETCHING_DEFAULT_STOCKS_DETAILS = 'FETCHING_DEFAULT_STOCKS_DETAILS';
export const FETCHING_DEFAULT_STOCKS_DETAILS_FAILURE = 'FETCHING_DEFAULT_STOCKS_DETAILS_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAIL = 'SEARCH_REQUEST_FAIL';

export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST';
export const STOCK_DETAILS_REQUEST_SUCCESS = 'STOCK_DETAILS_REQUEST_SUCCESS';
export const STOCK_DETAILS_REQUEST_FAILED = 'STOCK_DETAILS_REQUEST_FAILED';