export const SET_STOCK_DATA = 'SET_STOCK_DATA';
export const FETCHING_DEFAULT_STOCKS_DETAILS = 'FETCHING_DEFAULT_STOCKS_DETAILS';
export const FETCHING_DEFAULT_STOCKS_DETAILS_FAILURE = 'FETCHING_DEFAULT_STOCKS_DETAILS_FAILURE';